# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  ramus-benchmarks:
    dependencies:
    - base == 4.*
    - ramus
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: Ramus is a direct port of purescript-signal into Haskell, offering the Elm signal system for Haskell.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: NickSeagull/ramus
library:
  dependencies:
  - base == 4.*
  source-dirs: library
license: MIT
maintainer: Nikita Tchayka
name: ramus
synopsis: Elm signal system for Haskell
tests:
  ramus-test-suite:
    dependencies:
    - base == 4.*
    - ramus
    - hspec
    - QuickCheck
    - quickcheck-io
    - async
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.1.2'
